home/urls.py
from django.urls import path,include
from . import views


from django.conf import settings
from django.conf.urls.static import static

app_name='home'
#views.course_list()
urlpatterns = [
    path('',views.show_home,name='home') ,

]

learn/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='learn'
#views.course_list()
urlpatterns = [
    path('',views.post_learn,name="learn") ,
    path('blog',views.blog, name="blog"),
    path('blog/<pk>', views.blog_detail, name="blog_detail"),


]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static




urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('course/', include('course.urls' , namespace='course')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('learn/', include('learn.urls', namespace='learn')),
    path('home/', include('home.urls', namespace='home')),
    path('',include('chatbots.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learn/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

from django.db import models
from taggit.managers import TaggableManager

# Create your models here.


DIFFCALITY_TYPE = (
    ('easy','easy'),
    ('medium','medium'),
    ('hard','hard'),
)

SEMESTER_TYPE = (
    ('Semester 5', 'Semester 5'),
    ('Semester 6', 'Semester 6'),
    ('Semester 7', 'Semester 7'),
    ('Semester 8', 'Semester 8'),
    ('Semester 9', 'Semester 9'),
    ('Semester 10', 'Semester 10'),
)


CATEGORY_TYPE = (
    ('SW subjects', 'SW subjects'),
    ('Optional subjects', 'Optional subjects'),
    ('Others', 'Others'),

)

def image_upload(instance, filename):
    imagename , extension = filename.split(".")
    return "learn_Image/%s.%s"%(instance.id , extension)

def Video_upload(instance, filename):
    file , extension = filename.split(".")
    return "learn_Video/%s.%s"%(instance.id , extension)





class learn(models.Model): # table
    title= models.CharField(max_length=100); # reperesent a column
    description = models.TextField(default='write a description')
    urlLearn= models.URLField(max_length = 200)
    published_at = models.DateTimeField(auto_now=True)
    category= models.CharField(max_length=100, choices=CATEGORY_TYPE, default='SW subjects')
    diffcality_type=models.CharField(max_length=15,choices=DIFFCALITY_TYPE,default='easy')
    semester_type = models.CharField(max_length=15, choices=SEMESTER_TYPE, default='Semester 5')
    image= models.ImageField(upload_to=image_upload)
    videofile = models.FileField(upload_to='videos/', null=True)
    tags = TaggableManager()
    author= models.ForeignKey(User, on_delete=models.CASCADE,null=True,default=1)


    def __str__(self):
        return self.title

learn/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import learn




class LearnForm(forms.ModelForm):
    class Meta:
        model = learn
        fields= ['title','description','urlLearn','category','diffcality_type','semester_type',
                 'image','videofile','tags']

learn/views.py
from django.shortcuts import render
from .forms import LearnForm
from django.contrib.auth.decorators import login_required

from .models import learn
from django.http import HttpResponse
from django.core.paginator import Paginator
from taggit.models import Tag
from django.views.decorators.csrf import ensure_csrf_cookie
from .filters import LearnFilter

# Create your views here.

@login_required
def post_learn(request):
    if request.method=='POST':
        form = LearnForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            # Without this next line the tags won't be saved.
            form.save_m2m()
    else:
        form = LearnForm()


    context = {'form':form}
    return render(request, 'learn/post_learn.html',context)
@ensure_csrf_cookie
def blog(request):
    blog_list = learn.objects.all()
    myfilter = LearnFilter(request.GET, queryset= blog_list)
    blog_list = myfilter.qs

    paginator = Paginator(blog_list, 3) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'learn': page_obj , 'myfilter' : myfilter}
    return render(request,'blog/blog.html', context)


def blog_detail(request, pk):
    blog_detail= learn.objects.get(id=pk)
    context = {'learn': blog_detail}  # here the name goes to the templete
    return render(request, 'blog/single-blog.html', context)

learn/templates/blog/blog.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<style>
 .bradcam_bg_1 {
  background-image: url(../static/img/banner/bradcam.jpg);
}
</style>

   <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>blog</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->


    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                    {% for learns in learn %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="/media/{{learns.image}}" width="400px" height="400px" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3> {{learns.published_at|date:"d"}}</h3>
                                    <p> {{learns.published_at|date:"M "}}</p>
                                </a>
                            </div>
                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'learn:blog_detail' pk=learns.pk %}">
                                    <h2>{{learns.title}}</h2>
                                </a>
                                <p>That dominion stars lights dominion divide years for fourth have don't stars is that
                                    he earth it first without heaven in place seed it second morning saying.</p>

                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-book"></i>{{learns.category}}</a></li>
                                    <li><a href="#"><i class="fa fa-graduation-cap"></i>{{learns.semester_type}}</a></li>
                                     <li><a href="#"><i class="fa fa-tasks"></i>{{learns.diffcality_type}}</a></li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}

                        {% if learn.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if learn.has_previous%}
                                           <li><a href="?page={{learn.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                         {% for i in learn.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                         {% if learn.has_next %}
                                            <li><a href="?page={{learn.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                         {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>

                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                <input type="submit" value="Search" class="boxed-btn3 w-100 mt-2">
                            </form>
                        </aside>




                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->


{% endblock body %}

learn/templates/blog/single-blog.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block body %}
<style>
 .bradcam_bg_1 {
  background-image: url(../../static/img/banner/bradcam.jpg);
}
</style>

  <!-- bradcam_area  -->
  <div class="bradcam_area bradcam_bg_1">
      <div class="container">
          <div class="row">
              <div class="col-xl-12">
                  <div class="bradcam_text">
                      <h3>single blog</h3>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!--/ bradcam_area  -->

   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding center">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="card-img rounded-0" src="/media/{{learn.image}}" width="400px" height="400px" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{learn.title}}</h2>
                     <ul class="blog-info-link mt-3 mb-4">
                           <li><a href="#"><i class="fa fa-book"></i>{{learn.category}}</a></li>
                           <li><a href="#"><i class="fa fa-graduation-cap"></i>{{learn.semester_type}}</a></li>
                          <li><a href="#"><i class="fa fa-tasks"></i>{{learn.diffcality_type}}</a></li>
                     </ul>
                     <p class="excert">{{learn.description}}</p>
                     <p><a href="{{learn.urlLearn}}">{{learn.urlLearn}}</a></p>

                 <video class="embed-responsive embed-responsive-16by9" controls="controls" preload="preload">
                     <source src="/media/{{learn.videofile}}" type="video/mp4" />
                 </video>
                  </div>
               </div>
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <p class="like-info"><span class="align-middle"><i class="fa fa-heart"></i></span> Lily and 4
                        people like this</p>
                     <div class="col-sm-4 text-center my-2 my-sm-0">
                        <!-- <p class="comment-count"><span class="align-middle"><i class="fa fa-comment"></i></span> 06 Comments</p> -->
                     </div>
                     <ul class="social-icons">
                        <li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                     </ul>
                  </div>

            </div>



         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->

  {% endblock body %}