accounts/urls.py
from django.urls import include, path

from . import views

app_name='course'

urlpatterns = [
    path('signup',views.signup ,name='signup'),
    path('profile', views.profile, name='profile'),
    path('profile/edit', views.profile_edit, name='profile_edit'),
]

contact/urls.py
from django.urls import path,include
from . import views



app_name='contact'
#views.course_list()
urlpatterns = [
    path('',views.show_contact,name="contact") ,

]

course/urls.py
from django.urls import path,include
from . import views


from django.conf import settings
from django.conf.urls.static import static

app_name='course'
#views.course_list()
urlpatterns = [
    path('',views.course_list,name='course') ,
    path('<pk>',views.course_detail,name="course_detail"),
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include
from . import views


from django.conf import settings
from django.conf.urls.static import static

app_name='home'
#views.course_list()
urlpatterns = [
    path('',views.show_home,name='home') ,

]

learn/urls.py
from django.urls import path,include
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name='learn'
#views.course_list()
urlpatterns = [
    path('',views.post_learn,name="learn") ,
    path('blog',views.blog, name="blog"),
    path('blog/<pk>', views.blog_detail, name="blog_detail"),


]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static




urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('course/', include('course.urls' , namespace='course')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('learn/', include('learn.urls', namespace='learn')),
    path('home/', include('home.urls', namespace='home')),
    path('',include('chatbots.urls')),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>SE Assistance</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylebot.css' %}">
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->

</head>

<style>
 .bradcam_bg_1 {
  background-image: url(../static/img/banner/bradcam.jpg);
}
    .footer .footer_top {
    padding-top: 63px;
    padding-bottom: 40px;
}


</style>
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">

                                    <nav>
                                        <ul id="navigation" style="font-size:20px">
                                            <li><a href="{% url 'home:home'%}" style="font-size:20px">home</a></li>
                                            <li><a href="{% url 'course:course'%}" style="font-size:20px">Browse course</a></li>
                                            <li><a href="{% url 'contact:contact' %}" style="font-size:20px">faculty members </a></li>
                                            <li><a href="{% url 'learn:blog' %}" style="font-size:20px">blog</a></li>

                                        </ul>
                                    </nav>

                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                     {% if request.user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'logout' %}">Logout</a>

                                        </div>
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'accounts:profile' %}">profile</a>

                                        </div>
                                    {% else %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'login' %}">Log in</a>
                                        </div>
                                         <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'accounts:signup' %}">Sign up</a>
                                        </div>
                                    {% endif %}

                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'learn:learn' %}">Post a video or project</a>
                                    </div>

                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->
     <!-- begin of block  -->
    {% block body %}
    {% endblock body %}
     <!-- End of block  -->

    <!-- begin of chatbot  -->

<div class="container">

    <div class="chatbox">
        <div class="chatbox__support">
            <div class="chatbox__header">
                <div class="chatbox__image--header">
                    <img src="https://img.icons8.com/color/48/000000/circled-user-female-skin-type-5--v1.png" alt="image">
                </div>
                <div class="chatbox__content--header">
                    <h4 class="chatbox__heading--header">Chat support</h4>
                    <p class="chatbox__description--header">Hi. My name is SW assistance. How can I help you?</p>
                </div>
            </div>
            <div class="chatbox__messages">
                <div></div>
            </div>
            <div class="chatbox__footer">
                <input class="msq_content" type="text" placeholder="Write a message...">
                <button class="chatbox__send" method="POST">Send</button>
            </div>
        </div>
        <div class="chatbox__button">
            <button><img src="static/img/chatbox-icon.svg" /></button>
        </div>
    </div>
       <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
</div>



     <!-- end  of chatbot  -->

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>

                            <div class="socail_links">
                                <ul>

                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>

                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                pages
                            </h3>
                            <ul>
                                <li><a href="{% url 'learn:blog' %}">blog </a></li>
                                <li><a href="{% url 'contact:contact' %}"> faculty members</a></li>
                                <li><a href="{% url 'course:course'%}">browse course</a></li>

                            </ul>

                        </div>
                    </div>


                </div>
            </div>
        </div>

    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
     <script src="{% static 'js/tagsinput.js' %}"></script>
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js"></script>
    <!-- <script src="js/gijgo.min.js"></script> -->
    <script src="{% static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>

templates/base_generic.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>SE Assistance</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylebot.css' %}">
    <link rel="stylesheet" href="{% static 'css/tagsinput.css' %}" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->

</head>

<style>
 .bradcam_bg_1 {
  background-image: url(../static/img/banner/bradcam.jpg);
}
    .footer .footer_top {
    padding-top: 63px;
    padding-bottom: 40px;
}


</style>
<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">

                                    <nav>
                                        <ul id="navigation" style="font-size:20px">
                                            <li><a href="{% url 'home:home'%}" style="font-size:20px">home</a></li>
                                            <li><a href="#" style="font-size:20px">Browse course</a></li>
                                            <li><a href="{% url 'contact:contact' %}" style="font-size:20px">faculty members </a></li>
                                            <li><a href="{% url 'learn:blog' %}" style="font-size:20px">blog</a></li>

                                        </ul>
                                    </nav>

                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                     {% if request.user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'logout' %}">Log out</a>
                                        </div>
                                    {% else %}
                                        <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'login' %}">Log in</a>
                                        </div>
                                         <div class="phone_num d-none d-xl-block">
                                            <a href="{% url 'accounts:signup' %}">Sign up</a>
                                        </div>
                                    {% endif %}

                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'learn:learn' %}">Post a video or project</a>
                                    </div>

                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

{% block body %}
<style>
 .bradcam_bg_1 {
  background-image: url(../static/img/banner/bradcam.jpg);
}
</style>

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">

        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                      {% block content %}
                      {% endblock content %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}
   <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>

                            <div class="socail_links">
                                <ul>

                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>

                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                pages
                            </h3>
                            <ul>
                                <li><a href="{% url 'learn:blog' %}">blog </a></li>
                                <li><a href="{% url 'contact:contact' %}"> faculty members</a></li>
                                <li><a href="#">browse course</a></li>

                            </ul>

                        </div>
                    </div>


                </div>
            </div>
        </div>

    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
     <script src="{% static 'js/tagsinput.js' %}"></script>
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js"></script>
    <!-- <script src="js/gijgo.min.js"></script> -->
    <script src="{% static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/main.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>